#https://github.com/easingthemes/ssh-deploy
name: SSH Deploy to Ubuntu VPS

on: 
 push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{secrets.CONTABO_SSH_01232023_1}}
          ARGS: "-rlgoDzvc -i --delete"
          REMOTE_HOST: "xyz.alenev.name"
          REMOTE_USER: "admin"
          SOURCE: ""
          TARGET: "/home/admin/web/laravelvueorderscrudlumenmicroservice.alenev.name/public_html"
          EXCLUDE: "/.git/, /.github/, /vendor/, .env, /database/database.sqlite, .htaccess"
    - name: Configure SSH
      run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
      env:
          SSH_USER: "admin"
          SSH_KEY: ${{ secrets.CONTABO_SSH_01232023_1 }}
          SSH_HOST: "laravelvueorderscrudlumenmicroservice.alenev.name"
    - name: Composer update
      run: | 
          ssh -T staging 'cd /home/admin/web/laravelvueorderscrudlumenmicroservice.alenev.name/public_html && composer update'